function epsilonU = epsilonU(x,y)
%EPSILONU
%    EPSILONU = EPSILONU(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-Jun-2023 13:42:33

t2 = x.*pi;
t3 = y.*pi;
t4 = cos(t2);
t5 = cos(t3);
t6 = sin(t2);
t7 = sin(t3);
t8 = (t4.*t7.*pi)./2.0;
t9 = (t5.*t6.*pi)./2.0;
t10 = t8+t9;
epsilonU = reshape([t4.*t7.*pi,t10,t10,t5.*t6.*pi],[2,2]);
