function f2 = f2(x,y,lambda,mu)
%F2
%    F2 = F2(X,Y,LAMBDA,MU)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    21-Jun-2023 13:42:33

t2 = x.*pi;
t3 = y.*pi;
f2 = cos(t2).*cos(t3).*(lambda+mu).*(-9.869604401089358)+sin(t2).*sin(t3).*(lambda+mu.*3.0).*9.869604401089358;
