function uey = uey(x,y)
%UEY
%    UEY = UEY(X,Y)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    20-Jun-2023 08:14:06

uey = -x+(y.^2.*3.0)./(x+y.^3+1.0)-x.*y.*2.0+x.^2+cos(y.*7.0).*sin(x.*5.0).*7.0+1.0;
